package es.predictia.gfs;

public enum GridName {
	
	/** (1000 975 950 925 900.. 70 50 30 20 10) absolute vorticity [1/s] */ absvprs,
	/** surface best (4 layer) lifted index [k] */ no4lftxsfc,
	/** 500 mb 5-wave geopotential height [gpm] */ no5wavh500mb,
	/** surface convective precipitation [kg/m^2] */ acpcpsfc,
	/** surface albedo [%] */ albdosfc,
	/** surface total precipitation [kg/m^2] */ apcpsfc,
	/** surface convective available potential energy [j/kg] */ capesfc,
	/** 180-0 mb above ground convective available potential energy [j/kg] */ cape180_0mb,
	/** 255-0 mb above ground convective available potential energy [j/kg] */ cape255_0mb,
	/** surface categorical freezing rain [-] */ cfrzrsfc,
	/** surface categorical ice pellets [-] */ cicepsfc,
	/** surface convective inhibition [j/kg] */ cinsfc,
	/** 180-0 mb above ground convective inhibition [j/kg] */ cin180_0mb,
	/** 255-0 mb above ground convective inhibition [j/kg] */ cin255_0mb,
	/** (1000 975 950 925 900.. 300 250 200 150 100) cloud mixing ratio [kg/kg] */ clwmrprs,
	/** surface percent frozen precipitation [%] */ cpofpsfc,
	/** surface convective precipitation rate [kg/m^2/s] */ cpratsfc,
	/** surface categorical rain [-] */ crainsfc,
	/** surface categorical snow [-] */ csnowsfc,
	/** entire atmosphere (considered as a single layer) cloud water [kg/m^2] */ cwatclm,
	/** entire atmosphere (considered as a single layer) cloud work function [j/kg] */ cworkclm,
	/** surface downward long-wave rad. flux [w/m^2] */ dlwrfsfc,
	/** 2 m above ground dew point temperature [k] */ dpt2m,
	/** surface downward short-wave radiation flux [w/m^2] */ dswrfsfc,
	/** surface field capacity [fraction] */ fldcpsfc,
	/** surface ground heat flux [w/m^2] */ gfluxsfc,
	/** surface wind speed (gust) [m/s] */ gustsfc,
	/** surface geopotential height [gpm] */ hgtsfc,
	/** (1000 975 950 925 900.. 70 50 30 20 10) geopotential height [gpm] */ hgtprs,
	/** pv=2e-06 (km^2/kg/s) surface geopotential height [gpm] */ hgt2pv,
	/** pv=-2e-06 (km^2/kg/s) surface geopotential height [gpm] */ hgtneg2pv,
	/** highest tropospheric freezing level geopotential height [gpm] */ hgttop0c,
	/** 0c isotherm geopotential height [gpm] */ hgt0c,
	/** max wind geopotential height [gpm] */ hgtmwl,
	/** tropopause geopotential height [gpm] */ hgttrop,
	/** surface haines index [numeric] */ hindexsfc,
	/** 3000-0 m above ground storm relative helicity [m^2/s^2] */ hlcy3000_0m,
	/** surface planetary boundary layer height [m] */ hpblsfc,
	/** max wind icao standard atmosphere reference height [m] */ icahtmwl,
	/** tropopause icao standard atmosphere reference height [m] */ icahttrop,
	/** surface ice cover [proportion] */ icecsfc,
	/** surface land cover (0=sea, 1=land) [proportion] */ landsfc,
	/** surface surface lifted index [k] */ lftxsfc,
	/** surface latent heat net flux [w/m^2] */ lhtflsfc,
	/** mean sea level mslp (eta model reduction) [pa] */ msletmsl,
	/** (400 350 300 250 200.. 70 50 30 20 10) ozone mixing ratio [kg/kg] */ o3mrprs,
	/** surface potential evaporation rate [w/m^2] */ pevprsfc,
	/** 255-0 mb above ground pressure of level from which parcel was lifted [pa] */ plpl255_0mb,
	/** 0.995 sigma level potential temperature [k] */ potsig995,
	/** surface precipitation rate [kg/m^2/s] */ pratesfc,
	/** low cloud bottom level pressure [pa] */ preslclb,
	/** low cloud top level pressure [pa] */ preslclt,
	/** middle cloud bottom level pressure [pa] */ presmclb,
	/** middle cloud top level pressure [pa] */ presmclt,
	/** high cloud bottom level pressure [pa] */ preshclb,
	/** high cloud top level pressure [pa] */ preshclt,
	/** surface pressure [pa] */ pressfc,
	/** 80 m above ground pressure [pa] */ pres80m,
	/** pv=2e-06 (km^2/kg/s) surface pressure [pa] */ pres2pv,
	/** pv=-2e-06 (km^2/kg/s) surface pressure [pa] */ presneg2pv,
	/** convective cloud bottom level pressure [pa] */ prescclb,
	/** convective cloud top level pressure [pa] */ prescclt,
	/** max wind pressure [pa] */ presmwl,
	/** tropopause pressure [pa] */ prestrop,
	/** mean sea level pressure reduced to msl [pa] */ prmslmsl,
	/** entire atmosphere (considered as a single layer) precipitable water [kg/m^2] */ pwatclm,
	/** (1000 975 950 925 900.. 70 50 30 20 10) relative humidity [%] */ rhprs,
	/** 2 m above ground relative humidity [%] */ rh2m,
	/** 0.33-1 sigma layer relative humidity [%] */ rhsg330_1000,
	/** 0.44-1 sigma layer relative humidity [%] */ rhsg440_1000,
	/** 0.72-0.94 sigma layer relative humidity [%] */ rhsg720_940,
	/** 0.44-0.72 sigma layer relative humidity [%] */ rhsg440_720,
	/** 0.995 sigma level relative humidity [%] */ rhsig995,
	/** 30-0 mb above ground relative humidity [%] */ rh30_0mb,
	/** entire atmosphere (considered as a single layer) relative humidity [%] */ rhclm,
	/** highest tropospheric freezing level relative humidity [%] */ rhtop0c,
	/** 0c isotherm relative humidity [%] */ rh0c,
	/** surface sensible heat net flux [w/m^2] */ shtflsfc,
	/** surface snow depth [m] */ snodsfc,
	/** 0-0.1 m below ground volumetric soil moisture content [fraction] */ soilw0_10cm,
	/** 0.1-0.4 m below ground volumetric soil moisture content [fraction] */ soilw10_40cm,
	/** 0.4-1 m below ground volumetric soil moisture content [fraction] */ soilw40_100cm,
	/** 1-2 m below ground volumetric soil moisture content [fraction] */ soilw100_200cm,
	/** 2 m above ground specific humidity [kg/kg] */ spfh2m,
	/** 80 m above ground specific humidity [kg/kg] */ spfh80m,
	/** 30-0 mb above ground specific humidity [kg/kg] */ spfh30_0mb,
	/** surface sunshine duration [s] */ sunsdsfc,
	/** entire atmosphere total cloud cover [%] */ tcdcclm,
	/** boundary layer cloud layer total cloud cover [%] */ tcdcblcll,
	/** low cloud layer total cloud cover [%] */ tcdclcll,
	/** middle cloud layer total cloud cover [%] */ tcdcmcll,
	/** high cloud layer total cloud cover [%] */ tcdchcll,
	/** convective cloud layer total cloud cover [%] */ tcdcccll,
	/** 2 m above ground maximum temperature [k] */ tmax2m,
	/** 2 m above ground minimum temperature [k] */ tmin2m,
	/** low cloud top level temperature [k] */ tmplclt,
	/** middle cloud top level temperature [k] */ tmpmclt,
	/** high cloud top level temperature [k] */ tmphclt,
	/** surface temperature [k] */ tmpsfc,
	/** (1000 975 950 925 900.. 70 50 30 20 10) temperature [k] */ tmpprs,
	/** 1829 m above mean sea level temperature [k] */ tmp_1829m,
	/** 2743 m above mean sea level temperature [k] */ tmp_2743m,
	/** 3658 m above mean sea level temperature [k] */ tmp_3658m,
	/** 2 m above ground temperature [k] */ tmp2m,
	/** 80 m above ground temperature [k] */ tmp80m,
	/** 100 m above ground temperature [k] */ tmp100m,
	/** 0.995 sigma level temperature [k] */ tmpsig995,
	/** 30-0 mb above ground temperature [k] */ tmp30_0mb,
	/** pv=2e-06 (km^2/kg/s) surface temperature [k] */ tmp2pv,
	/** pv=-2e-06 (km^2/kg/s) surface temperature [k] */ tmpneg2pv,
	/** max wind temperature [k] */ tmpmwl,
	/** tropopause temperature [k] */ tmptrop,
	/** entire atmosphere (considered as a single layer) total ozone [du] */ tozneclm,
	/** 0-0.1 m below ground soil temperature validation to deprecate [k] */ tsoil0_10cm,
	/** 0.1-0.4 m below ground soil temperature validation to deprecate [k] */ tsoil10_40cm,
	/** 0.4-1 m below ground soil temperature validation to deprecate [k] */ tsoil40_100cm,
	/** 1-2 m below ground soil temperature validation to deprecate [k] */ tsoil100_200cm,
	/** surface zonal flux of gravity wave stress [n/m^2] */ ugwdsfc,
	/** surface momentum flux, u-component [n/m^2] */ uflxsfc,
	/** (1000 975 950 925 900.. 70 50 30 20 10) u-component of wind [m/s] */ ugrdprs,
	/** 1829 m above mean sea level u-component of wind [m/s] */ ugrd_1829m,
	/** 2743 m above mean sea level u-component of wind [m/s] */ ugrd_2743m,
	/** 3658 m above mean sea level u-component of wind [m/s] */ ugrd_3658m,
	/** 10 m above ground u-component of wind [m/s] */ ugrd10m,
	/** 80 m above ground u-component of wind [m/s] */ ugrd80m,
	/** 100 m above ground u-component of wind [m/s] */ ugrd100m,
	/** 0.995 sigma level u-component of wind [m/s] */ ugrdsig995,
	/** 30-0 mb above ground u-component of wind [m/s] */ ugrd30_0mb,
	/** pv=2e-06 (km^2/kg/s) surface u-component of wind [m/s] */ ugrd2pv,
	/** pv=-2e-06 (km^2/kg/s) surface u-component of wind [m/s] */ ugrdneg2pv,
	/** planetary boundary layer u-component of wind [m/s] */ ugrdpbl,
	/** max wind u-component of wind [m/s] */ ugrdmwl,
	/** tropopause u-component of wind [m/s] */ ugrdtrop,
	/** surface upward long-wave rad. flux [w/m^2] */ ulwrfsfc,
	/** top of atmosphere upward long-wave rad. flux [w/m^2] */ ulwrftoa,
	/** 6000-0 m above ground u-component storm motion [m/s] */ ustm6000_0m,
	/** surface upward short-wave radiation flux [w/m^2] */ uswrfsfc,
	/** top of atmosphere upward short-wave radiation flux [w/m^2] */ uswrftoa,
	/** surface meridional flux of gravity wave stress [n/m^2] */ vgwdsfc,
	/** surface momentum flux, v-component [n/m^2] */ vflxsfc,
	/** (1000 975 950 925 900.. 70 50 30 20 10) v-component of wind [m/s] */ vgrdprs,
	/** 1829 m above mean sea level v-component of wind [m/s] */ vgrd_1829m,
	/** 2743 m above mean sea level v-component of wind [m/s] */ vgrd_2743m,
	/** 3658 m above mean sea level v-component of wind [m/s] */ vgrd_3658m,
	/** 10 m above ground v-component of wind [m/s] */ vgrd10m,
	/** 80 m above ground v-component of wind [m/s] */ vgrd80m,
	/** 100 m above ground v-component of wind [m/s] */ vgrd100m,
	/** 0.995 sigma level v-component of wind [m/s] */ vgrdsig995,
	/** 30-0 mb above ground v-component of wind [m/s] */ vgrd30_0mb,
	/** pv=2e-06 (km^2/kg/s) surface v-component of wind [m/s] */ vgrd2pv,
	/** pv=-2e-06 (km^2/kg/s) surface v-component of wind [m/s] */ vgrdneg2pv,
	/** planetary boundary layer v-component of wind [m/s] */ vgrdpbl,
	/** max wind v-component of wind [m/s] */ vgrdmwl,
	/** tropopause v-component of wind [m/s] */ vgrdtrop,
	/** planetary boundary layer ventilation rate [m^2/s] */ vratepbl,
	/** 6000-0 m above ground v-component storm motion [m/s] */ vstm6000_0m,
	/** (1000 975 950 925 900.. 300 250 200 150 100) vertical velocity (pressure) [pa/s] */ vvelprs,
	/** 0.995 sigma level vertical velocity (pressure) [pa/s] */ vvelsig995,
	/** pv=2e-06 (km^2/kg/s) surface vertical speed shear [1/s] */ vwsh2pv,
	/** pv=-2e-06 (km^2/kg/s) surface vertical speed shear [1/s] */ vwshneg2pv,
	/** tropopause vertical speed shear [1/s] */ vwshtrop,
	/** surface water runoff [kg/m^2] */ watrsfc,
	/** surface water equivalent of accumulated snow depth [kg/m^2] */ weasdsfc,
	/** surface wilting point [fraction] */ wiltsfc,
	/** 2 m above ground desc [unit] */ var00212m;
	
}
